export const ERROR_CODES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    SUCCESS: 'SUCCESS',
    ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    ERR_FORBIDDEN: 'ERR_FORBIDDEN',
    ERR_INTERNAL_API_ERROR: 'ERR_INTERNAL_API_ERROR',
    ERR_CONFLICT: 'ERR_CONFLICT',
    ERR_UNIQUE_CONSTRAINT_VIOLATION: 'ERR_UNIQUE_CONSTRAINT_VIOLATION',
    ERR_MISSING_REQUIRED_ATTRIBUTES: 'ERR_MISSING_REQUIRED_ATTRIBUTES',
};

export const ERROR_MESSAGES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_FORBIDDEN: 'ERR_FORBIDDEN',
    USER_ALREADY_EXISTS: 'Email Id already exists',
    ERR_CONFLICT: 'ERR_CONFLICT',
    ERR_RESOURCE_NOT_FOUND: 'ERR_RESOURCE_NOT_FOUND',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
    ERR_UNIQUE_CONSTRAINT_VIOLATION: 'ERR_UNIQUE_CONSTRAINT_VIOLATION',
    ERR_MISSING_REQUIRED_ATTRIBUTES: 'ERR_MISSING_REQUIRED_ATTRIBUTES',

};

export const ERROR_MSG_STRINGS = {
    RESOURCE_NOT_FOUND: 'Resource not found',
};

export default {
    ERROR_CODES,
    ERROR_MESSAGES,
    ERROR_MSG_STRINGS,
};
